name: Mente_medica
description: medical assistance
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_login: ^1.0.14
    
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  intl: ^0.16.1
  # dummy package to test https://github.com/NearHuscarl/flutter_login/issues/35
  provider: ^4.0.1
  random_color: ^1.0.5
  pin_view: ^1.0.1
  pin_code_fields: ^3.1.2
  flare_flutter: ^1.7.1
  curved_navigation_bar: ^0.3.3
  intro_screen_onboarding_flutter: ^0.1.5
  deivao_drawer: ^1.0.0+6
  flutter_swiper: ^1.1.6
  fl_chart: ^0.10.0
  carousel_images: ^1.0.3
  carousel_pro: ^1.0.0
  flutter_circular_chart: ^0.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/images/


  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SourceSansPro-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/fonts/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceSansPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/SourceSansPro-Regular.ttf
        - asset: assets/fonts/SourceSansPro-Italic.ttf
          style: italic
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSansPro-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceSansPro-BoldItalic.ttf
          weight: 700
          style: italic
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700